version: "3.7"

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /srv/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Vancouver
    restart: always
    network_mode: host

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - /srv/mqtt/config:/mosquitto/config
      - /srv/mqtt/data:/mosquitto/data
      - /srv/mqtt/log:/mosquitto/log
    environment:
      - TZ=America/Vancouver
    restart: always

  bimmer2mqtt:
    container_name: bimmer2mqtt
    build: ./bimmer2mqtt
    environment:
      - BIMMER_USERNAME=BIMMER_USERNAME
      - BIMMER_PASSWORD=BIMMER_PASSWORD
      - BIMMER_VIN=1
      - MQTT_SERVER=mqtt
      - MQTT_PORT=1883
      - REGION=NORTH_AMERICA
      - LOG_LEVEL=INFO
    restart: always
    depends_on:
      - mqtt
